--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.791.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2022. 05. 13. 3:29:40
-- Server version: 10.4.24
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO ingatlan.ingatlanok(id, kategoria, leiras, hirdetesDatuma, tehermentes, ar, kepUrl) VALUES
(1, 1, 'Kertvárosi részén, egyszintes házat kínálunk nyugodt környezetben, nagy telken.', '2022-02-21', 1, 26990000, 'http://localhost:3000/adv01.jpg'),
(2, 1, 'Belvárosi környezetben, árnyékos helyen kis méretú családi ház eladó. Tömegközlekedéssel könnyen megközelíthető.', '2022-02-28', 1, 28990000, 'http://localhost:3000/adv02.jpg'),
(3, 2, 'Kétszintes berendezett lakás a belvárosban kiadó.', '2022-02-24', 1, 32000000, 'http://localhost:3000/adv03.jpg'),
(4, 4, 'Nagy garázs kertvárosi környezetben kiadó', '2022-02-26', 1, 5990000, 'http://localhost:3000/adv04.jpg'),
(5, 5, '10 hektáros mezőhazdasági terület eladó.', '2022-03-18', 1, 79000000, 'http://localhost:3000/adv05.jpg'),
(6, 6, 'Felújításra szoruló üzemcsarnok zöld környezetben áron alul eladó', '2022-02-23', 0, 25000000, 'http://localhost:3000/adv06.jpg');


INSERT INTO ingatlan.kategoriak(id, nev) VALUES
(1, 'Ház'),
(2, 'Lakás'),
(3, 'Építési telek'),
(4, 'Garázs'),
(5, 'Mezőgazdasági terület'),
(6, 'Ipari ingatlan');